### ISSUE TITLE
bert_st is not a registered name for Predictor.

### ISSUE THREAD

**Issue by Miracy** [yym6472/bert_slot_tagging#1]
Hello, I will delete the encoder in the configuration file.
After training through train.py, run test.py, the following error appears.

Traceback (most recent call last):
  File "E:/PycharmWorkSpace/GithubCode/bert_slot_tagging-master/test.py", line 28, in <module>
    main(args)
  File "E:/PycharmWorkSpace/GithubCode/bert_slot_tagging-master/test.py", line 20, in main
    predictor = Predictor.from_archive(archive=archive, predictor_name="bert_st")
  File "F:\Anaconda\envs\python36\lib\site-packages\allennlp\predictors\predictor.py", line 288, in from_archive
    return Predictor.by_name(predictor_name)(model, dataset_reader)
  File "F:\Anaconda\envs\python36\lib\site-packages\allennlp\common\registrable.py", line 97, in by_name
    raise ConfigurationError(f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: 'bert_st is not a registered name for Predictor. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.'

Looking forward to your reply, thanks!

**Comment by yym6472** [comment]
Hi, you may change the `@Predictor.register("slot_filling_predictor")` in [predictors.py#L9](https://github.com/yym6472/bert_slot_tagging/blob/master/predictors.py#L9) to `@Predictor.register("bert_st")`. AllenNLP needs the user to call `Predictor.register` function so it can find the Predictor's implementation by name.

**Comment by Miracy** [comment]
That's OK. Thank you!
